repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # - id: ruff
      #   args: [--fix]
      #   language_version: python3.11
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.9
    hooks:
      - id: uv-export
