version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: general_ledger_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
