version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: general_ledger_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: general_ledger_frontend
    restart: always
    ports:
      - "3000:3000"
      

  postgres:
    image: postgres:15
    container_name: general_ledger_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
