"""Fix default timestamps for accounts and ledger_entries

Revision ID: 07b140577523
Revises: 504e622f7d8b
Create Date: 2025-03-25 08:48:57.058572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "07b140577523"
down_revision: Union[str, None] = "504e622f7d8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "accounts",
        "created_at",
        server_default=text("now()"),
        existing_type=sa.DateTime(timezone=True),
    )

    op.alter_column(
        "ledger_entries",
        "created_at",
        server_default=text("now()"),
        existing_type=sa.DateTime(timezone=True),
    )

    op.alter_column(
        "ledger_entries",
        "updated_at",
        server_default=text("now()"),
        existing_type=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts",
        "created_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "ledger_entries",
        "created_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "ledger_entries",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###
