"""Add date field to ledger entries

Revision ID: 0b5824501de8
Revises: 88b4b8ff4de7
Create Date: 2025-03-25 08:35:26.358792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b5824501de8"
down_revision: Union[str, None] = "88b4b8ff4de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ledger_entries", sa.Column("date", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ledger_entries", "date")
    # ### end Alembic commands ###
