"""Add date field to account entry

Revision ID: 504e622f7d8b
Revises: 0b5824501de8
Create Date: 2025-03-25 08:39:06.997903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "504e622f7d8b"
down_revision: Union[str, None] = "0b5824501de8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "accounts",
        "created_at",
        server_default=text("now()"),
        existing_type=sa.DateTime(timezone=True),
    )

    op.alter_column(
        "ledger_entries",
        "created_at",
        server_default=text("now()"),
        existing_type=sa.DateTime(timezone=True),
    )

    op.alter_column(
        "ledger_entries",
        "updated_at",
        server_default=text("now()"),
        existing_type=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts",
        "created_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "ledger_entries",
        "created_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "ledger_entries",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###
