"""Add idempotency_key to ledger entries

Revision ID: 88b4b8ff4de7
Revises: 2e6306603419
Create Date: 2025-03-25 08:06:36.936069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88b4b8ff4de7"
down_revision: Union[str, None] = "2e6306603419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ledger_entries",
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
    )
    op.create_unique_constraint(
        "uq_ledger_entry_idempotency_key", "ledger_entries", ["idempotency_key"]
    )
    op.create_unique_constraint(None, "ledger_entries", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ledger_entries", type_="unique")
    op.drop_constraint(
        "uq_ledger_entry_idempotency_key", "ledger_entries", type_="unique"
    )
    op.drop_column("ledger_entries", "idempotency_key")
    # ### end Alembic commands ###
